### ISSUE TITLE
CSTEM Logo

### ISSUE THREAD

**Issue by JamesIsaacks** [SJS-Game-Sim/CSTEM#38]
CSTEM Logo is needed for branding of the project.

@C-STEM-Texas

**Comment by SJDNewton** [comment]
![CSTEM_logo_stacked (1)](https://user-images.githubusercontent.com/93950343/141200198-2a4492f3-0e71-43a5-8ea7-ae7ee259d3b4.png)

**Comment by C-STEM-Texas** [comment]
Cool Beans!
