### ISSUE TITLE
ItemHunt Images

### ISSUE THREAD

**Issue by JamesIsaacks** [SJS-Game-Sim/CSTEM#39]
Images of project parts are needed for the Item Hunt game.

These should be small, profile images of the parts. Images may need conversion or be used to make vector drawings.

@C-STEM-Texas

**Comment by SJDNewton** [comment]
I'm about to post a link to an archive of images, review them and let me know which ones you pull so I can get descriptions for you.

**Comment by SJDNewton** [comment]
![Uploading Black bottle caps .jpg…](
![DC motor ](https://user-images.githubusercontent.com/93950343/141356171-78395d6a-3dcc-44e7-ade7-0effa2d5cb76.jpg)
![LED light](https://user-images.githubusercontent.com/93950343/141356209-08a2ece6-4e13-4b71-a092-a98ea2583464.jpg)
![Graph paper (HS)](https://user-images.githubusercontent.com/93950343/141356216-81bb393b-83a2-4101-8a64-7d40b246b1a9.jpg)
)
![Chip Board](https://user-images.githubusercontent.com/93950343/141356223-afba9aaf-9af6-4005-9c30-86d7a7cd627d.jpg)

**Comment by SJDNewton** [comment]
![AA Battery   Holder](https://user-images.githubusercontent.com/93950343/141356296-112ac219-1d58-41a7-a046-cd7f6426ddd9.jpg)
![Black bottle caps ](https://user-images.githubusercontent.com/93950343/141356327-35cb26a2-9611-461a-ac01-d3dc9f532863.jpg)

**Comment by SJDNewton** [comment]
![Big wheels ](https://user-images.githubusercontent.com/93950343/141356558-40ff08a3-7093-457a-be51-1340e8dac92f.jpg)
![Crimpler pliers ](https://user-images.githubusercontent.com/93950343/141356583-a295e869-af7c-4e8a-bc32-e5b13db56698.jpg)
![DC Motor gearbox ](https://user-images.githubusercontent.com/93950343/141356619-3c1c59f4-0703-4add-a4cf-dbab86b93168.jpg)
![Duct tape](https://user-images.githubusercontent.com/93950343/141356644-f5ebebed-319d-475d-9b8a-cdbf776b0f4f.jpg)

![Switch ](https://user-images.githubusercontent.com/93950343/141356659-54be268e-49e3-4ad2-b05e-31e79e930a71.jpg)

**Comment by SJDNewton** [comment]
![Microbit ](https://user-images.githubusercontent.com/93950343/141356925-e8e2f4cb-743f-4d37-ae95-01851edd3e8f.jpg)
![12_ ruler ](https://user-images.githubusercontent.com/93950343/141356944-f45e4877-4b57-43b2-b6b9-1e755a5ba1e8.jpg)
![Elmer's glue](https://user-images.githubusercontent.com/93950343/141356961-3e5e7ca1-411e-4db9-b540-6cd0c68a6493.jpg)

**Comment by SJDNewton** [comment]
Starting from the top down for names: 
DC Motor
Grid Paper
Chip Board
AA Batteries and holder
Black caps
Big Wheels
Crimpler pliers
DC motor gearbox
Duck Tape
Switch
Microbit
12_ruler
Elmer's glue

**Comment by SJDNewton** [comment]
![H Bridge stepper motor drive board ](https://user-images.githubusercontent.com/93950343/142284396-4bda98b0-c75b-40c9-b2e2-8985aedcfbfd.jpg
![DC Motor Mount](https://user-images.githubusercontent.com/93950343/142284452-a2750c2f-8144-4d74-aa3b-737968fe0770.jpg)
![3V battery ](https://user-images.githubusercontent.com/93950343/142284473-acb57a18-c715-4c4d-9d8c-2232e6b03b9b.jpg)
![Joystick ](https://user-images.githubusercontent.com/93950343/142284488-247beb64-25d5-410e-a080-cf79337084c4.jpg)
)
![4FRH9_AS02](https://user-images.githubusercontent.com/93950343/142284500-26a3cb86-08a6-4a3c-9a82-87b444e455bf.jpeg)

**Comment by SJDNewton** [comment]
![H Bridge stepper motor drive board ](https://user-images.githubusercontent.com/93950343/142284585-13d4a6fc-b831-4f3b-aab9-e4ae112f110b.jpg)

**Comment by SJDNewton** [comment]
From top to bottom:
DC motor mount
3V battery
Joystick
Splice Connector
H Bridge stepper

**Comment by SJDNewton** [comment]
![U shaped wire Connector](https://user-images.githubusercontent.com/93950343/142285466-1a7767a5-2167-477e-89f9-ded4b3d4aa82.jpg)

"U" shaped wire connector

**Comment by SJDNewton** [comment]
https://drive.google.com/drive/folders/1ixOeVU3Xvtinr8Qdlvwu1wz4WYFvvPq5?usp=sharing
