### ISSUE TITLE
Final mockup for Assembly UI

### ISSUE THREAD

**Issue by Claripup** [SJS-Game-Sim/CSTEM#46]
A final mockup for the assembly game layout is needed

**Comment by Claripup** [comment]
![UI_Assembly_Final](https://user-images.githubusercontent.com/70114725/143729479-712b178a-cab1-4a9e-9ad5-60cece5f1ad9.png)

**Comment by Claripup** [comment]
@JamesIsaacks for review

**Comment by JamesIsaacks** [comment]
Need to explore how it may look with more items to choose from for assembly.

**Comment by Claripup** [comment]
![UI_Assembly_Final2](https://user-images.githubusercontent.com/70114725/144544116-5bd195c5-53ee-4f52-85de-afee61e2216e.png)

**Comment by Claripup** [comment]
added what more items would look like and added a background piece as requested

**Comment by Claripup** [comment]
@JamesIsaacks for review
