### ISSUE TITLE
Final mockup for Scratch-Like UI

### ISSUE THREAD

**Issue by Claripup** [SJS-Game-Sim/CSTEM#48]
A final mockup for the scratch-like game layout is needed

**Comment by Claripup** [comment]
![UI_ScratchLike_Final](https://user-images.githubusercontent.com/70114725/143729458-87c76d03-fb1d-4beb-a37f-7934f9754b77.png)

**Comment by Claripup** [comment]
@JamesIsaacks for review

**Comment by JamesIsaacks** [comment]
Should show objective. Should have a some button to run or check the order.

Please explore options on this.

**Comment by Claripup** [comment]
![UI_ScratchLike_Final2](https://user-images.githubusercontent.com/70114725/144574063-f800fc0b-e73a-4e3b-82d0-0512dc2068cc.png)

**Comment by Claripup** [comment]
Layout was redone and background piece was added

**Comment by Claripup** [comment]
@JamesIsaacks for review

**Comment by Claripup** [comment]
![UI_ScratchLike_Final3](https://user-images.githubusercontent.com/70114725/145907955-8b5279e4-051c-4214-a197-fd3e541e549c.png)

**Comment by Claripup** [comment]
Requested layout changes were made and new bubbles were made

**Comment by Claripup** [comment]
@JamesIsaacks for review

**Comment by Claripup** [comment]
Changes were approved
